apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-poc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-poc-app
  template:
    metadata:
      labels:
        app: devops-poc-app
    spec:
      containers:
        - name: app
          image: itsmeteja9/devops-poc-app:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
